### ISSUE TITLE
FTBFS with recent perl

### ISSUE THREAD

**Issue by formorer** [sni/Monitoring-Livestatus#1]
Hi Sven, 

I do maintain the lib in debian and during rebuilds we encountered that the testsuite fails:

  Thread 2 terminated abnormally: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at t/20-Monitoring-Livestatus-test_socket.t line 315, <GEN1> line 4.
  failed to connect at t/20-Monitoring-Livestatus-test_socket.t line 156.

See http://bugs.debian.org/838976 for details. Could you please take a look? Otherwise I will check the details as soon as I find some spare time. 

Thanks
Alex

**Comment by sni** [comment]
Turns out this is a problem when using JSON::XS in combination with perl threads in latest perl 5.24. Since threads are not supported by JSON::XS and we only use threads in the test cases, we simply turn this test off.
I just uploaded a new release to cpan.
